/* Ctmebc — content data (in-memory) */
window.CTMEBC = {
  brand: {
    name: "Ctmebc",
    nameZh: "嘉寀萌商務中心",
    tagline: "專業空間 · 高效連結 · 共創價值",
    company: "嘉寀萌有限公司",
    founder: "陳筱豌",
    founded: "2016年10月",
    phone: "04-XXXX-XXXX",
    email: "service@ctmebc.com.tw",
    address: "臺中市北區中清路一段 89 號 15 樓之 1",
    fb: "https://www.facebook.com/ctmebc22021455/?locale=zh_TW",
  },

  nav: [
    { id: "about", label: "關於我們" },
    { id: "services", label: "服務介紹" },
    { id: "space", label: "空間設備" },
    { id: "pricing", label: "方案與價格" },
    { id: "location", label: "位置交通" },
    { id: "faq", label: "常見問題" },
  ],

  pillars: [
    { icon: "home",     zh: "安心信賴",  en: "Trust & Reliability",      desc: "近 10 年商務中心經驗，全場無障礙、合法消防安全配置。" },
    { icon: "users",    zh: "專業高效",  en: "Professional & Efficient", desc: "從場地配置到設備支援一條龍，省去您每一分準備時間。" },
    { icon: "chart",    zh: "商務支援",  en: "Business Support",         desc: "公司登記、會計帳務、企業連結，協助微型創業穩健起步。" },
    { icon: "handshake",zh: "共創價值",  en: "Co-create Value",          desc: "與創業頭家鬥陣成功，是我們最重視的長期合作精神。" },
  ],

  services: [
    {
      tag: "SPACE_01",
      title: "百人空間",
      capacity: "可容納 100 人",
      area: "近 45 坪",
      desc: "大開放式百人空間，搭配獨間講師休息室與沙發洽談區。適合課程講座、發表會、企業會議與大型聚會。",
      image: "空間 / 百人會議廳",
      tags: ["課程講座", "發表會", "派對", "會議"],
    },
    {
      tag: "SPACE_02",
      title: "辦公室出租",
      capacity: "1–10 人團隊",
      area: "彈性坪數",
      desc: "適合微型創業到 10 人團隊的獨立辦公空間，提供基本辦公桌椅、高速網路、會議室共享時數。",
      image: "空間 / 獨立辦公室",
      tags: ["長租", "彈性月租", "獨立空間"],
    },
    {
      tag: "SPACE_03",
      title: "虛擬辦公室",
      capacity: "公司登記用",
      area: "—",
      desc: "提供公司登記地址、郵件代收與秘書代接電話服務，建立專業商務形象，月繳彈性方案。",
      image: "服務 / 公司登記",
      tags: ["公司登記", "郵件代收", "秘書服務"],
    },
    {
      tag: "SPACE_04",
      title: "商務支援",
      capacity: "依需求客製",
      area: "—",
      desc: "會計帳務綜理、營業登記諮詢、創業顧問轉介，讓您專注核心業務發展。",
      image: "服務 / 商務支援",
      tags: ["帳務", "登記", "顧問"],
    },
  ],

  facilities: [
    { group: "辦公與會議", items: [
      { name: "折疊桌", qty: 28, note: "180 公分摺疊桌" },
      { name: "折疊椅", qty: 100, note: "" },
      { name: "黑板 / 白板", qty: 2, note: "藍黑綠紅白板筆 ×4" },
      { name: "投影機 + 投影幕", qty: 1, note: "HDMI 直接播放" },
      { name: "55 吋 4K 螢幕", qty: 1, note: "" },
      { name: "無線麥克風", qty: 3, note: "" },
      { name: "落地喇叭", qty: 2, note: "含擴大機" },
      { name: "雷射多功能事務機", qty: 1, note: "影印 / 列印 / 掃描" },
    ]},
    { group: "餐飲與休憩", items: [
      { name: "RO 冰溫熱飲水機", qty: 1, note: "咖啡 / 紅綠茶 / 奶茶包" },
      { name: "微波爐 + 烤箱", qty: 2, note: "氣炸烤箱可調溫" },
      { name: "冰箱", qty: 1, note: "冷藏 + 冷凍" },
      { name: "電磁爐", qty: 1, note: "非明火" },
      { name: "沙發休憩區", qty: 1, note: "公共空間" },
      { name: "桌遊", qty: 10, note: "矮人礦坑 / 心臟病 等" },
    ]},
    { group: "場地保障", items: [
      { name: "全場無障礙空間", qty: "", note: "" },
      { name: "電梯", qty: 3, note: "" },
      { name: "煙霧偵測 / 警報器", qty: "", note: "消防安全合規" },
      { name: "B3 免費平面車位", qty: 2, note: "" },
      { name: "500M / 200M WiFi", qty: "", note: "高速雙頻" },
      { name: "寵物友善", qty: "", note: "需配戴禮貌帶" },
    ]},
  ],

  pricing: [
    {
      featured: false,
      name: "虛擬辦公室",
      tag: "公司登記",
      price: "1,500",
      unit: "月",
      desc: "建立專業商務地址",
      features: [
        "公司登記地址",
        "郵件代收 / 代轉",
        "秘書代接電話",
        "包裹管理",
        "免費咨詢時數 1 hr / 月",
      ],
      cta: "了解方案",
    },
    {
      featured: true,
      name: "百人空間 · 平日",
      tag: "熱門推薦",
      price: "3,000",
      unit: "4 小時",
      desc: "週一～週五 4 小時時段",
      features: [
        "近 45 坪開放空間",
        "完整投影 / 音響 / 麥克風",
        "免費 B3 平面車位 ×2",
        "RO 飲水機 / 茶包零食",
        "獨間講師休息室",
      ],
      cta: "立即預訂",
    },
    {
      featured: false,
      name: "百人空間 · 假日",
      tag: "週末 / 國定假日",
      price: "4,000",
      unit: "4 小時",
      desc: "週五晚到週日 / 國定假日",
      features: [
        "近 45 坪開放空間",
        "完整投影 / 音響 / 麥克風",
        "免費 B3 平面車位 ×2",
        "現場人員依需求駐點",
        "彈性擺設 自由調整",
      ],
      cta: "立即預訂",
    },
  ],

  timeSlots: [
    { label: "上午時段", time: "08:00 – 12:00" },
    { label: "下午時段", time: "13:00 – 17:00" },
    { label: "晚上時段", time: "18:00 – 22:00" },
  ],

  activities: [
    { label: "課程講座", value: 50 },
    { label: "聚會",     value: 17 },
    { label: "派對",     value: 17 },
    { label: "會議",     value: 16 },
  ],

  faq: [
    { q: "如何預訂百人空間？",
      a: "於本網站填寫預訂表單或來電 04-XXXX-XXXX 洽詢。確認時段後將以信用卡（藍新金流第三方支付）完成付款，並由專人回覆訂單確認信。" },
    { q: "時段費用如何計算？",
      a: "平日每時段 3,000 元，假日每時段 4,000 元（皆未稅；發票 5% 另計）。週五晚上至週日及國定假日採假日價格。" },
    { q: "場地可否帶外食或飲食？",
      a: "可以，需收取場地清潔押金 300 元，活動結束保持清潔即全額退還。冰箱使用前請通知服務人員。" },
    { q: "可否寵物入場？",
      a: "本場地寵物友善。公狗請配戴禮貌帶，便溺需即時清理，活動結束請恢復原狀。" },
    { q: "退訂與更改政策？",
      a: "活動前 2 週通知變更可享有免費更期一次。如需更多平面車位、美容床或藍牙喇叭等器材，請提前 2 天告知。" },
    { q: "現場有什麼設備可使用？",
      a: "包含無線麥克風 ×3、落地喇叭 ×2、投影機、55 吋 4K 螢幕、雷射多功能事務機、白板等；筆電與投影筆請自備。" },
  ],

  testimonials: [
    { name: "L 老師", role: "企業內訓講師", quote: "場地配置非常完整，現場服務人員配合度高，學員上課動線也很舒適。" },
    { name: "Mr. Chen", role: "新創共同創辦人", quote: "從公司登記到會議室預訂一條龍，省下我們很多營運心力，CP 值很高。" },
    { name: "Y 小姐", role: "活動策劃", quote: "免費平面車位 + 公車站就在一樓，學員到場零壓力。下次活動會再租。" },
  ],
};
